// This file is automatically generated. Do not edit it directly.
import {createClient} from "@supabase/supabase-js";
import type {Database} from "./types";

const SUPABASE_URL = "https://swdzxaymzqtryuudiyyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3ZHp4YXltenF0cnl1dWRpeXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTgwODcsImV4cCI6MjA2NTUzNDA4N30.LBOS5DGLcTEKcoz7G7DlaDAFx_wlSAwIDP62vOYSy9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
